name: Build FractalsQt

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Qt
      uses: jurplel/install-qt-action@v2
      with:
        version: '5.12.2'
        host: 'linux'
        target: 'desktop'
        arch: 'gcc_64'

    - name: Install CMake
      run: sudo apt-get install -y cmake

    - name: Configure CMake
      run: cmake -DCMAKE_BUILD_TYPE=Release .

    - name: Build
      run: cmake --build . --config Release